source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘8.0’

target 'ALKO' do
end

[
  'RSKImageCropper',
  'QBImagePickerController',
  'Firebase',
  'Firebase/Core',
  'Firebase/Auth',
  'Firebase/Storage',
  'Firebase/Database',
  'Firebase/RemoteConfig',
  'Firebase/Messaging',
].each do |lib|
  pod lib
  pod ‘GoogleMaps’
end