source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'ALKO' do
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

end

[
  'RSKImageCropper',
  'QBImagePickerController',
  'Firebase',
  'Firebase/Core',
  'Firebase/Auth',
  'Firebase/Storage',
  'Firebase/Database',
  'Firebase/RemoteConfig',
  'Firebase/Messaging',
].each do |lib|
  pod lib
  pod ‘GoogleMaps’
  pod ‘GooglePlaces’
end
post_install do |installer|
  `rm -rf Pods/leveldb-library/port/win`
  installer.pods_project.targets.each do |target|
      if target.name == "React"
          target.remove_from_project
      end
      if target.name == 'yoga'
          target.build_configurations.each do |config|
              config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
              config.build_settings['GCC_WARN_64_TO_32_BIT_CONVERSION'] = 'NO'
          end
      end
  end
end
